[tool.ruff]
exclude = [
    ".venv",
    ".git",
    "__pycache__",
    "build",
    "dist",
    "venv",
]
lint.ignore = []
line-length = 120
lint.select = [
    "E",
    "F",
    "W",
    "I001",
]
src = ["./"]

[tool.ruff.format]
quote-style = "double"

