# Generated by Django 4.2.7 on 2023-12-28 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_code', models.CharField(default='', help_text='Shop id lấy từ shop code', max_length=500)),
                ('access_token', models.CharField(max_length=500)),
                ('refresh_token', models.CharField(max_length=500, null=True)),
                ('auth_code', models.CharField(max_length=500)),
                ('grant_type', models.CharField(default='authorized_code', max_length=500)),
                ('shop_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_token', models.CharField(max_length=255, null=True, verbose_name='Verify token')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
