# Generated by Django 4.2.7 on 2024-03-11 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlashShipPODVariantList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variant_id", models.IntegerField()),
                ("color", models.CharField(max_length=500)),
                ("size", models.CharField(max_length=200)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("SHIRT", "Shirt"),
                            ("HOODIE", "Hoodie"),
                            ("SWEATSHIRT", "Sweatshirt"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
