# Generated by Django 4.2.7 on 2024-03-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="pack_id",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
