# Generated by Django 4.2.7 on 2024-02-06 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupCustom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_name",
                    models.CharField(
                        default="chua co ten",
                        help_text="ten cua phong ban",
                        max_length=500,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="shop",
            name="group_custom_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.groupcustom",
            ),
        ),
        migrations.CreateModel(
            name="UserGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.IntegerField(
                        choices=[(0, "Admin"), (1, "Manager"), (2, "Seller")],
                        default=2,
                        verbose_name="Role",
                    ),
                ),
                (
                    "group_custom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.groupcustom",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "group_custom")},
            },
        ),
    ]
