# Generated by Django 4.2.7 on 2024-03-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_customusersendprint"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorCodes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=500)),
                ("message", models.CharField(max_length=500)),
                ("description", models.CharField(max_length=500)),
            ],
        )
    ]
