# Generated by Django 5.0.1 on 2024-01-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_key', models.CharField(default='', help_text='Appkey lấy từ tiktok app for developer', max_length=500)),
                ('secret', models.CharField(default='', help_text='app secret lấy từ tiktok app for developer', max_length=500)),
            ],
        ),
    ]
