# Generated by Django 4.2.7 on 2024-03-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_flashshippodvariantlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designsku",
            name="image_back",
            field=models.CharField(
                blank=True, help_text="image_back", max_length=500, null=True
            ),
        ),
        migrations.AlterField(
            model_name="designsku",
            name="image_front",
            field=models.CharField(
                blank=True, help_text="image_front", max_length=500, null=True
            ),
        ),
    ]
