# Generated by Django 4.2.7 on 2024-03-14 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_designsku_image_back_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("package_id", models.CharField(max_length=500)),
                ("buyer_first_name", models.CharField(blank=True, max_length=500)),
                ("buyer_last_name", models.CharField(blank=True, max_length=500)),
                ("buyer_email", models.EmailField(max_length=254)),
                ("buyer_phone", models.CharField(blank=True, max_length=200)),
                ("buyer_address1", models.CharField(blank=True, max_length=1000)),
                ("buyer_address2", models.CharField(blank=True, max_length=1000)),
                ("buyer_city", models.CharField(blank=True, max_length=500)),
                ("buyer_province_code", models.CharField(blank=True, max_length=20)),
                ("buyer_zip", models.CharField(blank=True, max_length=100)),
                ("buyer_country_code", models.CharField(max_length=2)),
                ("shipment", models.IntegerField()),
                ("linkLabel", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="ProductPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variant_id", models.IntegerField()),
                ("printer_design_front_url", models.URLField()),
                ("printer_design_back_url", models.URLField()),
                ("quantity", models.IntegerField()),
                ("note", models.CharField(blank=True, max_length=1000)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="api.package",
                    ),
                ),
            ],
        ),
    ]
