# Generated by Django 4.2.7 on 2024-02-15 04:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_shop_group_custom_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="templates",
            name="badWords",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(verbose_name=200), default=[], size=None
            ),
        ),
    ]
