# Generated by Django 4.2.7 on 2024-03-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_errorcodes_package_order_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="package_status",
            field=models.BooleanField(default=True),
        ),
    ]
