# Generated by Django 4.2.7 on 2024-04-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_package_package_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateDesign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.JSONField()),
            ],
        ),
    ]
