# Generated by Django 4.2.7 on 2024-03-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_package_productpackage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="linkLabel",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
