# Generated by Django 4.2.7 on 2024-04-15 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0005_templatedesign"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatedesign",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_template",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
