# Generated by Django 4.2.7 on 2024-01-15 04:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_template_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="category_id",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AddField(
            model_name="template",
            name="colors",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(verbose_name=20), default=[], size=None
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="description",
            field=models.TextField(default="", max_length=500),
        ),
        migrations.AddField(
            model_name="template",
            name="is_cod_open",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="template",
            name="name",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AddField(
            model_name="template",
            name="package_height",
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name="template",
            name="package_length",
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name="template",
            name="package_weight",
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name="template",
            name="package_width",
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name="template",
            name="sizes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(verbose_name=20), default=[], size=None
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(verbose_name=20), default=[], size=None
            ),
        ),
    ]
