# Generated by Django 4.2.7 on 2024-03-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_package_linklabel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productpackage",
            name="printer_design_back_url",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="productpackage",
            name="printer_design_front_url",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
