# Generated by Django 4.2.7 on 2024-04-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_package_package_status_templatedesign_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="shop_cipher",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="shop_id_author",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
