# Generated by Django 4.2.7 on 2024-03-14 04:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_productpackage_printer_design_back_url_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="package",
            old_name="package_id",
            new_name="order_id",
        ),
    ]
