# Generated by Django 4.2.7 on 2024-01-16 01:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_template_category_id_template_colors_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Template",
        ),
    ]
