# Generated by Django 4.2.7 on 2024-03-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_rename_package_id_package_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productpackage",
            name="printer_design_back_url",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="productpackage",
            name="printer_design_front_url",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
