# Generated by Django 4.2.7 on 2024-01-16 02:29

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0007_delete_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=500)),
                ("category_id", models.CharField(default="", max_length=500)),
                ("warehouse_id", models.CharField(default="", max_length=500)),
                ("description", models.TextField(default="", max_length=500)),
                ("is_cod_open", models.BooleanField(default=False)),
                ("package_height", models.FloatField(default=1)),
                ("package_length", models.FloatField(default=1)),
                ("package_weight", models.FloatField(default=1)),
                ("package_width", models.FloatField(default=1)),
                (
                    "sizes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(verbose_name=20),
                        default=[],
                        size=None,
                    ),
                ),
                (
                    "colors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(verbose_name=20),
                        default=[],
                        size=None,
                    ),
                ),
                (
                    "type",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(verbose_name=20),
                        default=[],
                        size=None,
                    ),
                ),
                ("types", models.JSONField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
