# Generated by Django 4.2.7 on 2024-01-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
            ],
        ),
    ]
