# Generated by Django 4.2.7 on 2024-05-09 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_notimessage_notification_is_read_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_data',
        ),
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.CharField(default='', max_length=255, null=True),
        ),
      
        migrations.CreateModel(
            name='ImageFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.imagefolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_image')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.imagefolder'),
        ),
    ]
