# Generated by Django 4.2.7 on 2024-05-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_image_image_data_image_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_name',
            field=models.CharField(default='no name', max_length=255, null=True),
        )
      
    ]
