# Generated by Django 4.2.7 on 2024-03-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_alter_productpackage_variant_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
