name: Backend CI/CD

on:
    pull_request:
        branches:
            - develop
    push:
        branches:
            - develop

jobs:
    checkout-code:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v3

    install-dependencies:
        runs-on: self-hosted
        needs: checkout-code
        steps:
            - name: If virtualenv exists, remove it
              run: |
                  if [ -d ".venv" ]; then
                      rm -rf .venv
                  fi
            - name: Create virtualenv and Setting up
              run: |
                  python -m venv .venv
                  source .venv/bin/activate
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt --no-cache-dir

    deploy:
        runs-on: self-hosted
        needs: install-dependencies
        steps:
            - name: Deploy
              run: |
                  echo "Activating virtualenv"
                  source .venv/bin/activate
                  echo "Deploying to production"
                  python manage.py runserver 0.0.0.0:8000
                  echo "Deployed successfully"
