name: Docker Image CI

on:
    push:
        branches:
            - dev

jobs:
    build:
        runs-on: self-hosted

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Build the Docker image
              run: |
                  docker build -t tiktokshop-folinas-fe .

            - name: Run Docker container
              run: |
                  docker run -p 80:5173 -d tiktokshop-folinas-fe
