name: Backend CI/CD

on:
    pull_request:
        branches:
            - develop
    push:
        branches:
            - develop

jobs:
    checkout-code:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v3

    install-dependencies:
        runs-on: self-hosted
        needs: checkout-code
        steps:
            - name: If virtualenv exists, remove it
              run: |
                  if [ -d ".venv" ]; then
                      rm -rf .venv
                  fi
            - name: Create virtualenv and Setting up
              run: |
                  python -m venv .venv
                  source .venv/bin/activate
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

    deploy:
        runs-on: self-hosted
        needs: install-dependencies
        steps:
            - name: Deploy
              run: |
                  if tmux has-session -t backend 2>/dev/null; then
                      echo "Backend tmux session already exists. Killing it."
                      tmux kill-session -t backend
                  fi
                  echo "Creating new backend tmux session."
                  tmux new-session -d -s backend

                  tmux send-keys -t backend "source .venv/bin/activate" C-m
                  tmux send-keys -t backend "python manage.py runserver" C-m

                  echo "Backend tmux session created and server started."
